version: '2'
services:
  server:
    build:
      context: ./
      dockerfile: deploy/server.docker
    hostname: 'server'
    container_name: 'server'
    entrypoint: /entrypoint.sh
    command: 'apache2-foreground'
    ports:
      - '80:80'
    volumes:
      - './:/var/www'
      - './deploy/entrypoint.sh:/entrypoint.sh'
      - './deploy/php.ini:/usr/local/etc/php/php.ini'
    depends_on:
      - db
    working_dir: '/var/www'
    links:
      - 'db:db'
    networks:
      - app

  db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DATABASE=test
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    image: 'postgres:9.6'
    container_name: 'db'
    ports:
      - '5432:5432'
    volumes:
      - './server/database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'


networks:
  app:
    driver: bridge

volumes:
  db-data:
  server-data:
