version: '2'
services:
  fssk-laravel-server:
    build:
      context: ./
      dockerfile: deploy/server.docker
    hostname: 'fssk-laravel-server'
    container_name: 'fssk-laravel-server'
    entrypoint: /server-entrypoint.sh
    env_file: ./server/.env
    command: 'apache2-foreground'
    ports:
      - '4000:80'
    volumes:
      - './:/var/www'
      - './deploy/server-entrypoint.sh:/server-entrypoint.sh'
      - './deploy/php.ini:/usr/local/etc/php/php.ini'
    depends_on:
      - fssk-laravel-db
    working_dir: '/var/www'
    links:
      - 'fssk-laravel-db:db'
    networks:
      - app
  fssk-laravel-client:
    build:
      context: ./
      dockerfile: deploy/client.docker
    hostname: 'fssk-laravel-client'
    container_name: 'fssk-laravel-client'
    env_file: ./client/.env
    command: 'npm start'
    ports:
      - '3000:3000'
    volumes:
      - './client:/opt/src'
    working_dir: '/opt/src'
    networks:
      - app
  fssk-laravel-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DATABASE=test
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    image: 'postgres:9.6'
    container_name: 'fssk-laravel-db'
    ports:
      - '5432:5432'
    volumes:
      - './server/database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  fssk-laravel-db-data:
  fssk-laravel-server-data:
