version: '2'
services:
  laravel-www:
    build: .
    hostname: 'laravel-www'
    container_name: 'laravel-www'
    entrypoint: /entrypoint.sh
    command: ["httpd-foreground"]
    ports:
      - '80:80'
    volumes:
      - './:/var/www'
      - './entrypoint.sh:/entrypoint.sh'
      - './php.ini:/etc/php/7.0/apache2/php.ini'
    depends_on:
      - laravel-postgres
    working_dir: '/var/www'
    links:
      - 'laravel-postgres:laravel-postgres'
    networks:
      - app

  laravel-postgres:
    environment:
      - POSTGRES_USER: root
      - POSTGRES_DB: test
      - POSTGRES_PASSWORD: admin
      - POSTGRES_HOST: localhost
      - POSTGRES_PORT: 5432
    image: 'postgres:9.6'
    container_name: 'laravel-postgres'
    ports:
      - '5432:5432'
    volumes:
      - './server/database/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'


networks:
  app:
    driver: bridge

volumes:
  laravel-postgres-data:
  laravel-www-data:
